{
  "headers": {
    "cleint-id": "senait",
    "cleint-secreite": "helomule",
    "content-type": "application/json",
    "user-agent": "PostmanRuntime/7.29.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "9a5eae85-e780-4a36-bb0c-e556a666ef41",
    "host": "localhost:8083",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive",
    "content-length": "817"
  },
  "clientCertificate": null,
  "method": "POST",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/api/Customer",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": null,
  "listenerPath": "/api/Customer",
  "localAddress": "/127.0.0.1:8083",
  "relativePath": "/api/Customer",
  "uriParams": {},
  "rawRequestUri": "/api/Customer",
  "rawRequestPath": "/api/Customer",
  "remoteAddress": "/127.0.0.1:50194",
  "requestPath": "/api/Customer"
}