[
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "2022-03-06T22:42:56.243-05:00"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "2022-03-06T22:42:56.259-05:00"
  },
  {
    "Client Key": "121212",
    " First Name": "michael",
    " Middle Name": "abebe",
    " Last Name": "yendaw",
    " BirthDate": "19810912",
    " Height": "167cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "121212",
    " First Name": "michael",
    " Middle Name": "abebe",
    " Last Name": "yendaw",
    " BirthDate": "19810912",
    " Height": "167cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "121212",
    " First Name": "michael",
    " Middle Name": "abebe",
    " Last Name": "yendaw",
    " BirthDate": "19810912",
    " Height": "167cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "121212",
    " First Name": "michael",
    " Middle Name": "abebe",
    " Last Name": "yendaw",
    " BirthDate": "19810912",
    " Height": "167cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "121212",
    " First Name": "michael",
    " Middle Name": "abebe",
    " Last Name": "yendaw",
    " BirthDate": "19810912",
    " Height": "167cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  },
  {
    "Client Key": "161616",
    " First Name": "elnathan",
    " Middle Name": "michael",
    " Last Name": "abebe",
    " BirthDate": "20120912",
    " Height": "163cm",
    " Weight": "140lb",
    " Billing Street": "384 copley dr",
    " Billing City": "lancaster",
    " Billing State": "pa",
    " Billing Postal Code": "17601",
    " Billing Country": "usa",
    " Created Date": "20220306"
  }
]